[shell.variables.installers.pacman]
commands = { install = "sudo pacman -Syu" }
packages = [
    "powerline",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
]

[shell.variables.installers.yay]
commands = { install = "yay -Syu" }
packages = ["oh-my-zsh-git"]
