[shell.variables.installers.pacman]
packages = [
    "powerline",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
]

[shell.variables.installers.pacman.commands]
install = "sudo pacman -Syu"
uninstall = "sudo pacman -Rns"

[shell.variables.installers.yay]
packages = ["oh-my-zsh-git"]

[shell.variables.installers.yay.commands]
install = "yay -Syu"
uninstall = "yay -Rns"
