[shell.variables.installers.pacman.commands]
install = "sudo pacman -Syu"
uninstall = "sudo pacman -Rns"

[shell.variables.installers.pacman]
packages = [
    "powerline",
    "zsh",
    "zsh-autosuggestions",
    "zsh-syntax-highlighting",
]

[shell.variables.installers.pamac.commands]
install = "sudo pamac install"
uninstall = "sudo pamac remove --no-confirm"

[shell.variables.installers.pamac]
packages = ["oh-my-zsh-git"]
