[helpers]
pre_installer = ".dotter/helpers/pre-installer.rhai"
package_installer = ".dotter/helpers/package-installer.rhai"
post_script_runner = ".dotter/helpers/post-script-runner.rhai"

[shell.files]
".dotter/scripts" = { target = "", type = "template" }
"shell/profile" = { target = "~/.profile", type = "template" }

[shell.variables]
install = true
uninstall = true

[nano]
depends = ["shell"]

[openssh]
depends = ["shell"]

[openssh.files]
"openssh/ssh-agent.service" = "~/.config/systemd/user/ssh-agent.service"

[bash]
depends = ["shell"]

[bash.files]
"bash/bash_profile" = { target = "~/.bash_profile", type = "symbolic" }

[bash.variables]

[zsh]
depends = ["shell"]

[powerline]
depends = ["zsh"]

[zsh-autosuggestions]
depends = ["zsh"]

[zsh-syntax-highlighting]
depends = ["zsh"]

[oh-my-zsh-git]
depends = ["zsh", "powerline", "zsh-autosuggestions", "zsh-syntax-highlighting"]

[oh-my-zsh-git.files]
"zsh/zprofile" = "~/.zprofile"
"zsh/zshrc" = { target = "~/.zshrc", type = "symbolic" }

[oh-my-zsh-git.variables]

[yay]
depends = ["shell"]

[git]
depends = ["shell"]

[git.files]
"git/gitconfig" = "~/.gitconfig"

[settings]
default_target_type = "automatic"
